const COREASPECTSIDS = ["courage", "evade", "fight", "luck", "perception"];
const ASPECTRATINGS = [-1, 0,1,2,3,4];
const ASPECTTN = [10, 9, 7, 5, 4];

const ARCHETYPEASPECTRATING = 4;

const DEFAULTMAXWOUNDS = 4;

const DEFAULTMAXHOSTOMENDICE = 13;

const DEFAULTDICEBAGCOUNT = {safe : 8, omen : 1 }

const DEFAULTACTOMENDCIETHRESHOLD = {
		0 : 0,
		1 : 1,
		2 : 4,
		3 : 8
};

const MAXFE = 2;

const MAXTD = 2;
const MINTD = -2;

const TASKRISKS = ["risky", "normal", "harmless"];

export const CONSTANTS = { COREASPECTSIDS, ASPECTRATINGS, ASPECTTN, ARCHETYPEASPECTRATING, DEFAULTMAXWOUNDS, DEFAULTMAXHOSTOMENDICE, DEFAULTDICEBAGCOUNT, DEFAULTACTOMENDCIETHRESHOLD, MAXFE, MAXTD, MINTD, TASKRISKS };